[[integrations]]
name = "snooty-cache-plugin"

# Production context: all deploys from the Production branch
# set in your site’s Branches settings in the UI will inherit
# these settings.
[context.production]
publish = "snooty/public"
command = ". ./build.sh"

[[redirects]]
  from = "https://master--fork2-docs-realm.netlify.app/"
  to = "https://mongodb.com/docs"
